---
user: www-data
group: www-data
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
port: 3000
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
chdir: /var/apps/feed_app
tag: feed-app
